base_url = "https://ncerone.com"
title = "Nicholas Cerone"
description = "Mechanical Engineering Portfolio"
default_language = "en"
theme = "project-portfolio"

compile_sass = true
build_search_index = true

[search]
index_format = "elasticlunr_json"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

taxonomies = [
    { name = "projects", paginate_by = 5, feed = true },
    { name = "skills", paginate_by = 5, feed = true }
]

[extra]
enable_theme_switching = true
daisyui_theme_light = "light"
daisyui_theme_dark = "dark"

[extra.navbar]
links = [
    { url = "projects", i18n_key = "projects" },
    { url = "skills", i18n_key = "skills" }
]